/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Conversor;

import javax.swing.JOptionPane;

/**
 *
 * @author Wilson Pop
 */
public class Conversore extends javax.swing.JFrame {

    /**
     * Creates new form Conversore
     */
    public Conversore() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dab = new javax.swing.JButton();
        dah = new javax.swing.JButton();
        dao = new javax.swing.JButton();
        Btd = new javax.swing.JButton();
        Bah = new javax.swing.JButton();
        OaD = new javax.swing.JButton();
        HaD = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ELIJA UNA OPCIÓN");

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("BIENVENIDO");

        dab.setText("Decimal a binario");
        dab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dabActionPerformed(evt);
            }
        });

        dah.setText("Decimal a hexadecimal");
        dah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dahActionPerformed(evt);
            }
        });

        dao.setText("Decimal a octal");
        dao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daoActionPerformed(evt);
            }
        });

        Btd.setText("Binario a decimal");
        Btd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtdActionPerformed(evt);
            }
        });

        Bah.setText("Binario a hexadecimal");
        Bah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BahActionPerformed(evt);
            }
        });

        OaD.setText("Octal a decimal");
        OaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OaDActionPerformed(evt);
            }
        });

        HaD.setText("Hexadecimal de decimal");
        HaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HaDActionPerformed(evt);
            }
        });

        jButton3.setText("Hexadecimal a Binario");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(dab, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dah)
                .addGap(18, 18, 18)
                .addComponent(dao, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(Btd, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bah, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(OaD))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(HaD)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dab)
                    .addComponent(dah)
                    .addComponent(dao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btd)
                    .addComponent(Bah)
                    .addComponent(OaD))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HaD)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dabActionPerformed
       String num=null;
       Conversiones CN = new Conversiones();
       num = JOptionPane.showInputDialog("Digite un número");
       JOptionPane.showMessageDialog(null,CN.intToBin(new Integer (num)) );
    }//GEN-LAST:event_dabActionPerformed

    private void dahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dahActionPerformed
        String num=null;
        Conversiones CH = new Conversiones();
        num = JOptionPane.showInputDialog("Digite un número");
        JOptionPane.showMessageDialog(null, CH.intToHex(new Integer (num)));
    }//GEN-LAST:event_dahActionPerformed

    private void daoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daoActionPerformed
        String num=null;
        Conversiones CO = new Conversiones();
        num = JOptionPane.showInputDialog("Digite un número");
        JOptionPane.showMessageDialog(null, CO.intToOct(new Integer(num)));
    }//GEN-LAST:event_daoActionPerformed

    private void BtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtdActionPerformed
        String num = null;
        Conversiones BD = new Conversiones();
        num= JOptionPane.showInputDialog(null,"Digite el número binario");
        JOptionPane.showMessageDialog(null, BD.Bintodec(new Integer(num)));
    }//GEN-LAST:event_BtdActionPerformed

    private void BahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BahActionPerformed
        String num = null;
        Conversiones BH = new Conversiones ();
        num = JOptionPane.showInputDialog(null, "Digite el número binario");
        JOptionPane.showMessageDialog(null, BH.Bintohex(new Integer(num)));
    }//GEN-LAST:event_BahActionPerformed

    private void OaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OaDActionPerformed
        String num=null;
        Conversiones OD = new Conversiones ();
        num= JOptionPane.showInputDialog(null, "Digite el número octal");
        JOptionPane.showMessageDialog(null,OD.Octodec(new Integer(num)));
        
    }//GEN-LAST:event_OaDActionPerformed

    private void HaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HaDActionPerformed
        String num=null;
        Conversiones HD = new Conversiones();
        num = JOptionPane.showInputDialog(null,"Digite el número hexadecimal");
        JOptionPane.showMessageDialog(null,HD.HextoD(num));
    }//GEN-LAST:event_HaDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String num=null;
        Conversiones HB = new Conversiones();
        num = JOptionPane.showInputDialog(null,"Digite el número hexadecimal");
        JOptionPane.showMessageDialog(null, HB.HEXTOBIN(num));
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversore().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bah;
    private javax.swing.JButton Btd;
    private javax.swing.JButton HaD;
    private javax.swing.JButton OaD;
    private javax.swing.JButton dab;
    private javax.swing.JButton dah;
    private javax.swing.JButton dao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
