/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package separadortokens;

import javax.swing.JOptionPane;

/**
 *
 * @author Wilson Pop
 */
public class Tokens extends javax.swing.JFrame {

    /**
     * Creates new form Tokens
     */
    public Tokens() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Entrada");

        jButton1.setText("Separar tokens");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String palabra = this.txt.getText();
        int r = 1;
        int a = 1;
        
        String car [] = new String [palabra.length()];
        
        String cadcar = "|";
        String lc = "|";
        String sdo = "|";
        String seo = "|";
        String sen = "|";
        String send = "|";
        String sim = "|";
        String simc = "|";
        
        
        
        for (int i = 0; i < palabra.length(); i++) {
            if ((palabra.charAt(i) == 'a') || (palabra.charAt(i) == 'b') || (palabra.charAt(i) == 'c') || (palabra.charAt(i) == 'd')
                    || (palabra.charAt(i) == 'e') || (palabra.charAt(i) == 'f') || (palabra.charAt(i) == 'g')
                    || (palabra.charAt(i) == 'h') || (palabra.charAt(i) == 'i') || (palabra.charAt(i) == 'j')
                    || (palabra.charAt(i) == 'k') || (palabra.charAt(i) == 'l') || (palabra.charAt(i) == 'm') || (palabra.charAt(i) == 'n')
                    || (palabra.charAt(i) == 'o') || (palabra.charAt(i) == 'p') || (palabra.charAt(i) == 'q')
                    || (palabra.charAt(i) == 'r') || (palabra.charAt(i) == 's') || (palabra.charAt(i) == 't')
                    || (palabra.charAt(i) == 'u') || (palabra.charAt(i) == 'v') || (palabra.charAt(i) == 'w')
                    || (palabra.charAt(i) == 'x') || (palabra.charAt(i) == 'y') || (palabra.charAt(i) == 'z')) {
                cadcar = cadcar + palabra.charAt(i)+" |";
                lc = lc + i + " |";
                
            }
            
           if ((palabra.charAt(i) == '+') || (palabra.charAt(i) == '-') || (palabra.charAt(i) == '/') || 
                   (palabra.charAt(i) == '*') || (palabra.charAt(i) == '=') || (palabra.charAt(i) == '^') 
                   || (palabra.charAt(i) == '>') || (palabra.charAt(i) == '<')) {
                sdo = sdo + palabra.charAt(i)+" |";
                seo = seo + i + " |";
                
            }
           
           if((palabra.charAt(i)== '0') || (palabra.charAt(i)== '1') || (palabra.charAt(i)== '2') || (palabra.charAt(i)== '3')
                   || (palabra.charAt(i)== '4') || (palabra.charAt(i)== '5') || (palabra.charAt(i)== '6') || (palabra.charAt(i)== '7') 
                   || (palabra.charAt(i)== '8')|| (palabra.charAt(i)== '9')){
               sen = sen + palabra.charAt(i) + " |";
               send = send + i + " |";
           
           }
           if((palabra.charAt(i)=='{')  || (palabra.charAt(i)=='}') || (palabra.charAt(i)=='[') || (palabra.charAt(i)==']')
                   || (palabra.charAt(i)=='(') || (palabra.charAt(i)==')')){
               sim = sim + palabra.charAt(i) + " |";
               simc = simc + i + " |";
               
               
           }
           
           
           
        }
        
        if (cadcar == "|"){
                cadcar = " Sin existencia";
                lc = " Sin existencia";
        
        }
        if(sdo == "|"){
                sdo = "Sin existencia";
                seo = "Sin existencia";
        }
        if (sen == "|"){
            sen = "Sin existencia";
            send = "Sin existencia";
        
        }
        
        if (sim == "|"){
                   sim = " Sin existencia";
                   simc = " Sin existencia";
               }
        
        
        
       JOptionPane.showMessageDialog(rootPane, "Identificadores:  "+cadcar + " ; Su posición:  " + lc + "\n"
       + "Operadores aritméticos:  " + sdo + " ; Su posición:  " + seo + "\n" + 
       "Números:  " + sen + " ; Su posición:  " + send + "\n" + " Símbolos:  " + sim + " ; Su posición:  " + simc );
        
       
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tokens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tokens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tokens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tokens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tokens().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
