/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete2;

import java.awt.BasicStroke;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.xy.XYLineAndShapeRenderer;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import paquete3.Conexion;
import proyectosimulacion1_wilsonpop.PantallaInicial;

/**
 *
 * @author Wilson Pop
 */
public class RegresionLineal extends javax.swing.JFrame {

    /**
     * Creates new form RegresionLineal
     */
    double x[];
    double x1[];
    double y[];
    double y11[];
    double xx1[];
    double yy1[];
    double xy[];
    double m = 0;
    double b = 0;
    double r = 0;
    double syx = 0;
    int numbers = 0;
    double sumx = 0;
    double sumy = 0;
    double sumxx = 0;
    double sumxy = 0;
    double sumyy1 = 0;
    double yfinal[];
    double xfinal[];
    int val1 = 0;
    int val2 = 0;
    int contador = 0;
    double restayy[];
    public String consulta;
    int interruptor = 0;

    DefaultTableModel modTabM = new DefaultTableModel(); // tabla 
    DefaultTableModel modTabM1 = new DefaultTableModel(); // tabla 

    public RegresionLineal() {
        initComponents();
        this.setLocationRelativeTo(null);

        String[] titulo = new String[]{"x", "y", "xy", "x^2"};
        modTabM.setColumnIdentifiers(titulo);
        tablaM.setModel(modTabM);

        String[] titulo1 = new String[]{"x1", "y1"};
        modTabM1.setColumnIdentifiers(titulo1);
        tablaM1.setModel(modTabM1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaM = new javax.swing.JTable();
        valy = new javax.swing.JButton();
        valx = new javax.swing.JButton();
        Nodatos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        y1 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        m1 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        r1 = new javax.swing.JLabel();
        Syx1 = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaM1 = new javax.swing.JTable();
        jx0 = new javax.swing.JTextField();
        jx1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lista1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablaM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaM);

        valy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valy.setText("Ingresar valores de y");
        valy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valyActionPerformed(evt);
            }
        });

        valx.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        valx.setText("Ingresar valores de x");
        valx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valxActionPerformed(evt);
            }
        });

        Nodatos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nodatos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NodatosKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("No. de datos");

        y1.setBackground(new java.awt.Color(255, 255, 255));
        y1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        y1.setForeground(new java.awt.Color(51, 102, 255));
        y1.setText("Formula:");
        y1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel1.setPreferredSize(new java.awt.Dimension(450, 230));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        m1.setBackground(new java.awt.Color(255, 255, 255));
        m1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        m1.setForeground(new java.awt.Color(255, 153, 0));
        m1.setText("m:");
        m1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        b1.setBackground(new java.awt.Color(255, 255, 255));
        b1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 153, 153));
        b1.setText("b:");
        b1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        r1.setBackground(new java.awt.Color(255, 255, 255));
        r1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        r1.setForeground(new java.awt.Color(102, 102, 102));
        r1.setText("r:");
        r1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Syx1.setBackground(new java.awt.Color(255, 255, 255));
        Syx1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Syx1.setText("Syx:");
        Syx1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel2.setPreferredSize(new java.awt.Dimension(450, 230));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        tablaM1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaM1);

        jx0.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jx0.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jx0KeyTyped(evt);
            }
        });

        jx1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jx1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jx1KeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("x0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("x1");

        lista1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lista1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Personas_Productos", "Productos_TotVentas", "Personas_TotVentas", "Producto_Precio_Hora", "ProductosHora_Precio", "CantProductos_TotVentas" }));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabla);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Calcular desde base de datos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(y1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(r1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Syx1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jx0, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jx1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(m1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(Nodatos, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(b1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(valy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lista1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Nodatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addComponent(m1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(valx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valy)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lista1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(y1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(r1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Syx1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jx0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PantallaInicial pant = new PantallaInicial();
        this.setVisible(false);
        pant.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            val1 = Integer.parseInt(jx0.getText());
            val2 = Integer.parseInt(jx1.getText());
            limpiarMatriz();
            limpiarMatriz3();
            CalcXY();
            DibujarLinea1();
            Sumatorias();
            LlenarMatriz3();
            Syx1();
            DibujarLinea2();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ocurrio un error intentelo de nuevo");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void valxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valxActionPerformed

        try {
            numbers = Integer.parseInt(Nodatos.getText());
            val1x();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Digitar un número en la entrada de cantidad de numeros");
        }

    }//GEN-LAST:event_valxActionPerformed

    private void valyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valyActionPerformed

        try {
            numbers = Integer.parseInt(Nodatos.getText());
            val2y();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Digitar un número en la entrada de cantidad de numeros");
        }
    }//GEN-LAST:event_valyActionPerformed

    public void val1x() {
        x = new double[numbers];
        x1 = new double[numbers];
        double aux = 0;

        for (int a = 0; a < numbers; a++) {
            aux = Double.valueOf(JOptionPane.showInputDialog("Ingrese valor " + a));
            x[a] = aux;
            x1[a] = aux;
            System.out.println(aux);
        }

    }

    public void val2y() {
        y = new double[numbers];
        y11 = new double[numbers];
        double aux = 0;

        for (int a = 0; a < numbers; a++) {
            aux = Double.valueOf(JOptionPane.showInputDialog("Ingrese valor " + a));
            y[a] = aux;
            y11[a] = aux;
        }
    }

    public void CalcXY() {
        CalculoRegresionLineal cal = new CalculoRegresionLineal();

        xy = new double[numbers];
        xx1 = new double[numbers];

        xy = cal.calcMult2(x, y);
        xx1 = cal.calcMult(x);

        LlenarMatriz();
    }

    public void LlenarMatriz() {
        for (int ctn = 0; ctn < numbers; ctn++) {
            modTabM.addRow(new Object[]{
                String.valueOf(x1[ctn]), String.valueOf(y[ctn]), String.valueOf(xy[ctn]), String.valueOf(xx1[ctn])
            });
        }
    }

    private void limpiarMatriz() {
        int filas = modTabM.getRowCount();
        for (int a = 0; a < filas; a++) {
            modTabM.removeRow(0);
        }
    }

    public void LlenarMatriz3() {
        CalculoRegresionLineal cal = new CalculoRegresionLineal();
        contador = 0;
        for (int ctn = val1; ctn < val2; ctn++) {
            modTabM1.addRow(new Object[]{
                String.valueOf(ctn), String.valueOf(cal.yx(m, ctn, b))
            });
            xfinal[contador] = ctn;
            yfinal[contador] = cal.yx(m, ctn, b);
            contador++;
        }
    }

    private void limpiarMatriz3() {
        int filas = modTabM1.getRowCount();
        for (int a = 0; a < filas; a++) {
            modTabM1.removeRow(0);
        }
    }

    public void DibujarLinea1() {
        XYSeries series = new XYSeries("Gráfica XY");

        XYSeriesCollection dtsc = new XYSeriesCollection();

        for (int re = 0; re < numbers; re++) {
            series.add(x1[re], y[re]);
        }

        dtsc.addSeries(series);

        JFreeChart grafica = ChartFactory.createScatterPlot("Valores XY originales", "X", "Y", dtsc, PlotOrientation.VERTICAL, true, false, false);

        ChartPanel pa = new ChartPanel(grafica);
        /*add(pa);
        pa.setBounds(0, 50, 600, 300);
        panel.add(pa, BorderLayout.NORTH);*/
        pa.setMouseWheelEnabled(true);
        pa.setPreferredSize(new Dimension(450, 230));
        panel1.setLayout(new BorderLayout());
        panel1.add(pa, BorderLayout.NORTH);
        pack();
        //repaint();    
    }

    public void DibujarLinea2() {
        XYSeries series = new XYSeries("Gráfica XY");

        XYSeriesCollection dtsc = new XYSeriesCollection();

        for (int re = 0; re < contador; re++) {
            series.add(xfinal[re], yfinal[re]);
        }

        dtsc.addSeries(series);

        XYLineAndShapeRenderer renderer = new XYLineAndShapeRenderer();
        renderer.setSeriesPaint(0, Color.DARK_GRAY);
        renderer.setSeriesStroke(0, new BasicStroke(2));

        JFreeChart grafica = ChartFactory.createXYLineChart("Valores XY transformados", "X", "Y", dtsc, PlotOrientation.VERTICAL, true, false, false);
        grafica.getXYPlot().setRenderer(renderer);

        ChartPanel pa = new ChartPanel(grafica);
        /*add(pa);
        pa.setBounds(0, 50, 600, 300);
        panel.add(pa, BorderLayout.NORTH);*/
        pa.setMouseWheelEnabled(true);
        pa.setPreferredSize(new Dimension(450, 230));
        panel2.setLayout(new BorderLayout());
        panel2.add(pa, BorderLayout.NORTH);
        pack();
        //repaint();    
    }

    public void Sumatorias() {
        CalculoRegresionLineal cal = new CalculoRegresionLineal();

        sumx = cal.Sum(x1, numbers);
        sumy = cal.Sum(y, numbers);
        sumxy = cal.Sum(xy, numbers);
        sumxx = cal.Sum(xx1, numbers);
        m = cal.m(sumxy, sumx, sumy, sumxx, numbers);
        b = cal.b(sumy, m, sumx, numbers);

        m1.setText("m: " + m);
        b1.setText("b: " + b);
        y1.setText("Y= " + m + "x" + " + (" + b + ")");

        yy1 = new double[numbers];
        yy1 = cal.calcMult(y11);

        sumyy1 = cal.Sum(yy1, numbers);

        r = cal.calR(sumxy, sumx, sumy, sumxx, sumyy1, numbers);

        r1.setText("r: " + r);

        //syx = cal.calSxy(sumx, sumy, sumxx, sumyy1, numbers, r);
        //syx = cal.yyresta2(y, sumy, numbers);
        //Syx1.setText("Syx: " + syx );
        yfinal = new double[val2];
        xfinal = new double[val2];

        System.out.println(sumx);
        System.out.println(sumy);
        System.out.println(sumxy);
        System.out.println(sumxx);
        System.out.println(m);
        System.out.println(b);

    }

    public void Syx1() {
        CalculoRegresionLineal cal = new CalculoRegresionLineal();
        syx = cal.yyresta2(y, yfinal, numbers);
        Syx1.setText("Syx: " + syx);
    }

    public void Consultas() {
        int lista  = lista1.getSelectedIndex();
        
        if(lista==0){
            consulta = "SELECT detEs.TOTAL_PERSONAS, detEs.CANTIDAD_PRODUCTOS FROM dbo.DETALLE_ESCENARIO as detEs;";
            interruptor = 1;
        }else if(lista==1){
            consulta = "select CANTIDAD_PRODUCTOS, TOTAL_VENTAS from dbo.DETALLE_ESCENARIO;";
            interruptor = 2;
        }else if (lista==2){
            consulta = "select TOTAL_PERSONAS, TOTAL_VENTAS from dbo.DETALLE_ESCENARIO;";
            interruptor = 2;
        }else if(lista==3){
            consulta = "select CANTIDAD_PRODUCTOS, PRECIO_TOTAL from dbo.PRODUCTOS_TIEMPO;";
            interruptor = 2;
        }else if(lista==4){
            consulta = "select CANTIDAD_DESPACHADA, PRECIO_TOTAL from dbo.VENTAS_INDIVIDUALES;";
            interruptor = 2;
        }else if(lista==5){
            consulta = "select dth.CANTIDAD_PRODUCTOS, dth.TOTAL_VENTA from dbo.DETALLE_HORA as dth;";
            interruptor = 2;
        }        
 
        try {
            cargar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegresionLineal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cargar() throws ClassNotFoundException {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        modelo.setRowCount(0);

        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        try {
            Connection con = Conexion.getConexion();
            ps = con.prepareStatement(consulta);

            rs = ps.executeQuery();

            rsmd = rs.getMetaData();

            columnas = rsmd.getColumnCount();

            modelo.setColumnCount(columnas);

            while (rs.next()) {
                Object[] fila = new Object[columnas];
                for (int i = 0; i < columnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }

    }


    private void NodatosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NodatosKeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_NodatosKeyTyped

    private void jx0KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jx0KeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jx0KeyTyped

    private void jx1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jx1KeyTyped
        char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jx1KeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Consultas();
        ObtenerDatos();
    }//GEN-LAST:event_jButton3ActionPerformed

    public void ObtenerDatos() {
        DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
        int cols = modelo.getColumnCount();
        int fils = modelo.getRowCount();
        numbers = fils;
        x = new double[fils];
        x1 = new double[fils];
        y = new double[fils];
        y11 = new double[fils];
        double aux1=0;
        double aux2=0;
                
        for(int i=0;i<fils;i++){
            
            if(interruptor==1){
                aux1 = (int)modelo.getValueAt(i,0);
                aux2 = (int) modelo.getValueAt(i,1);            
            }else if (interruptor==2){
                aux1 = (int)modelo.getValueAt(i,0);
                aux2 = (double) modelo.getValueAt(i,1);  
            }
            
            x[i]=aux1;
            x1[i]=aux1;
            y[i]= aux2;
            y11[i] = aux2;
            System.out.println(aux1);
            System.out.println(aux2);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegresionLineal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegresionLineal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Nodatos;
    private javax.swing.JLabel Syx1;
    private javax.swing.JLabel b1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jx0;
    private javax.swing.JTextField jx1;
    private javax.swing.JComboBox<String> lista1;
    private javax.swing.JLabel m1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JLabel r1;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaM;
    private javax.swing.JTable tablaM1;
    private javax.swing.JButton valx;
    private javax.swing.JButton valy;
    private javax.swing.JLabel y1;
    // End of variables declaration//GEN-END:variables
}
