/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordenamientoswilson;

import javax.swing.JOptionPane;

/**
 *
 * @author Wilson Pop
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbx.setBackground(new java.awt.Color(102, 255, 204));
        cbx.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cbx.setForeground(new java.awt.Color(51, 51, 255));
        cbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Burbuja", "Quick Sort", "Fusión", "Inserción", "Gnome", "Todo" }));
        cbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxActionPerformed(evt);
            }
        });

        txt1.setBackground(new java.awt.Color(51, 255, 204));
        txt1.setColumns(20);
        txt1.setRows(5);
        jScrollPane1.setViewportView(txt1);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("INGRESAR DATOS A ORDENAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Resultados de las comparaciones:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setText("Seleccione la opción que desea calcular");

        jLabel3.setBackground(new java.awt.Color(255, 153, 153));
        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel3.setText("Por Wilson Pop");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(11, 11, 11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Algoritmos obj = new Algoritmos ();
        
        int i = cbx.getSelectedIndex();
        
        int da=0;
        String aux="";
        int cont =0;
        String das="";
        String bur="";
        String qui="";
        String gnm="";
        String quit="";
        String in="";
        int arglo [];
        int ar [];
        int er [];
        int ir[];
        int or[];
        String auxu="";
        String arglos ="";
        String rr[];
        String auxi="";
        int aux1 =0;
        int fu [] = new int [1];
        String uxi = "";
        double mm=0.0;
        String auxxo="";
        double acu []= new double [4];
        double ord = 0.0;
        double aci [] = new double [4];
        
        da=Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad de elementos númericos a ingresar"));
        das=Integer.toString(da);
        arglo = new int [da];
        rr = new String [da];
        ar = new int [da];    
        er = new int[da];
        ir = new int [da];
        or = new int [da];
        do{
            aux+=JOptionPane.showInputDialog("Ingrese el número: " + (cont+1) )+"/";
            cont++;
        }while(cont<da);
        cont=0;
       //aqui
        auxxo=aux;
        
        for(int r=0;r<aux.length();r++){
            auxu+=aux.charAt(r);
           // System.out.println(auxu);
            if(auxu.equals("/")){
                rr[cont]=auxi;
                auxi="";
                cont++;
                auxu="";
          }else{
                auxi +=aux.charAt(r);
                auxu="";
            }
            
          //  auxu="";
        }
        
        auxu="";
        auxi="";
        
        for(int t=0;t<cont;t++){
            auxu +=rr[t];
            aux1=Integer.parseInt(auxu);
            arglo[t]=aux1;
            ar[t]=aux1;
            er[t]=aux1;
            ir[t]=aux1;
            or[t]=aux1;
            auxu="";
            aux1=0;
        }
        
  //aqui      
        
        if(i==0){
            
            bur = "METODO BURBUJA\n"+"Tiempo:\n"+obj.Burbuja(aux,das,"1")+" segundos"+"\nComparaciones:\n"+obj.Burbuja(aux,das,"0");
            txt1.setText(bur);
            
        }else if(i==1){
            qui="METODO QUICKSORT\n"+"Tiempo:\n"+obj.Quicksort(arglo,0,arglo.length-1,1,0.0,0)+" segundos";
            quit="\nComparaciones:\n"+obj.Quicksort(ar,0,arglo.length-1,0,0.0,0);
            txt1.setText(qui+quit);
        }else if(i==2){
            fu = obj.Fusion(ar,0);
            auxi= "METODO DE FUSION\n"+ "\nComparaciones:\n"+ String.valueOf(fu[0]);
            txt1.setText(auxi);
            
        }else if(i==3){
            in = "METODO INSERCIÓN\n"+"Tiempo:\n"+obj.Insercion(aux,das,"1")+" segundos"+"\nComparaciones:\n"+obj.Insercion(aux,das,"0");
            txt1.setText(in);
        }else if(i==4){
            gnm="METODO INSERCIÓN\n"+"Tiempo:\n"+obj.Gnome(arglo,1)+" segundos"+"\nComparaciones:\n"+obj.Gnome(ar,0);
            txt1.setText(gnm);     
        }else if(i==5){
          bur =obj.Burbuja(aux,das,"1");  
          qui=obj.Quicksort(arglo,0,arglo.length-1,1,0.0,0);
          fu = obj.Fusion(ar,0);
          in =obj.Insercion(auxxo,das,"1");
          gnm = obj.Gnome(er,1);
         acu[0] = Double.valueOf(bur);
         acu[1] = Double.valueOf(qui);
         acu[2]= Double.valueOf(in);
         acu[3]= Double.valueOf(gnm);
         
         aci=acu;
          
              for(int x=0;x<acu.length-1;x++){
                        for(int y=0;y<acu.length-1;y++){
                            if(acu[y]>acu[y+1]){
                                ord=acu[y];
                                acu[y]=acu[y+1];
                                acu[y+1]=ord;
                            }
                        }
                    
                    }
         
 //parte para imprimir      
              if(acu[0]==aci[0]){
                  txt1.setText("El mejor es el método burbuja, su tiempo fue: "+ "\n" +bur + " segundos");
              }else if(acu[0]==aci[1]){
                  txt1.setText("El mejor es quicksort, su tiempo fue: " + "\n" +qui + " segungos");
              }else if(acu[0]==aci[2]){
                  txt1.setText("El mejor es el de inserción, su tiempo fue: " +"\n" +in + " segundos");
              }else if(acu[0]==aci[3]){
                  txt1.setText("El mejor es el genome, su tiempo fue: "+"\n" +gnm+ " segundos");
              }
          
        }else{}
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbx;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt1;
    // End of variables declaration//GEN-END:variables
}
