/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectosimulacion1_wilsonpop;

import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Wilson Pop
 */
public class Mm1 extends javax.swing.JFrame {

    TeoriaColas calcular = new TeoriaColas();

    double Tsllegada = 0.0;
    double TsServicio = 0;
    double Wq1 = 0;
    double Ws1 = 0;
    double Ls1 = 0;
    double Lq1 = 0;
    double P1 = 0;
    double p0 = 0;
    double Pn[];
    double tsL[];
    double tsS[];
    int tiempo = 0;
    int n = 0;
    String confirmar = "";

    double tiempoMinutos1 = 0;
    double tiempoMinutos2 = 0;

    DefaultTableModel modTabM = new DefaultTableModel(); // tabla 

    public Mm1() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);

        String[] titulo = new String[]{"n", "P(n)"};
        modTabM.setColumnIdentifiers(titulo);
        tablaM.setModel(modTabM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tasaLlegada = new javax.swing.JTextField();
        tasaServicio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Ls = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Wq = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Ws = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        P = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Po = new javax.swing.JTextField();
        Lq = new javax.swing.JTextField();
        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaM = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        n1 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Po1 = new javax.swing.JTextField();
        Po2 = new javax.swing.JTextField();
        Min = new javax.swing.JCheckBox();
        Sec = new javax.swing.JCheckBox();
        Min2 = new javax.swing.JCheckBox();
        Sec2 = new javax.swing.JCheckBox();
        Act3 = new javax.swing.JCheckBox();
        Act4 = new javax.swing.JCheckBox();
        Act1 = new javax.swing.JCheckBox();
        Act2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tasa de llegada");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tasa de servicio");

        tasaLlegada.setBackground(new java.awt.Color(204, 255, 255));

        tasaServicio.setBackground(new java.awt.Color(204, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Ls");

        Ls.setBackground(new java.awt.Color(204, 255, 255));
        Ls.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ls.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Lq");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Wq");

        Wq.setBackground(new java.awt.Color(204, 255, 255));
        Wq.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Wq.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Ws");

        Ws.setBackground(new java.awt.Color(204, 255, 255));
        Ws.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Ws.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("P");

        P.setBackground(new java.awt.Color(204, 255, 255));
        P.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        P.setEnabled(false);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Po");

        Po.setBackground(new java.awt.Color(204, 255, 255));
        Po.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Po.setEnabled(false);

        Lq.setBackground(new java.awt.Color(204, 255, 255));
        Lq.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Lq.setEnabled(false);

        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel1.setPreferredSize(new java.awt.Dimension(440, 240));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel2.setPreferredSize(new java.awt.Dimension(440, 240));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        tablaM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaM);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Calcular");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("n");

        n1.setBackground(new java.awt.Color(204, 255, 255));

        t1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("t");

        panel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("P(Wq>t)");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("P(Ws>t)");

        Po1.setBackground(new java.awt.Color(204, 255, 255));
        Po1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Po1.setEnabled(false);

        Po2.setBackground(new java.awt.Color(204, 255, 255));
        Po2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Po2.setEnabled(false);

        Min.setText("Minutos");

        Sec.setText("Segundos");

        Min2.setText("Minutos");

        Sec2.setText("Seguntos");

        Act3.setText("Activar");
        Act3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Act3ActionPerformed(evt);
            }
        });

        Act4.setText("Activar");
        Act4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Act4ActionPerformed(evt);
            }
        });

        Act1.setText("Activar");
        Act1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Act1ActionPerformed(evt);
            }
        });

        Act2.setText("Activar");
        Act2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Act2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Po1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Po2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(n1)
                            .addComponent(tasaServicio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tasaLlegada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Min)
                                .addGap(18, 18, 18)
                                .addComponent(Sec))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Min2)
                                .addGap(18, 18, 18)
                                .addComponent(Sec2)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Wq, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Ls, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Act1)
                            .addComponent(Act2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Lq, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Po, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ws, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(112, 131, Short.MAX_VALUE)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Act3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Act4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jButton1)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Act3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(Ls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Act1))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(Wq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Act2))
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Lq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Ws, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Act4))
                                        .addGap(23, 23, 23)
                                        .addComponent(Po, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(jLabel8)))))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tasaLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Min)
                            .addComponent(Sec))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tasaServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Min2)
                            .addComponent(Sec2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(7, 7, 7))
                            .addComponent(t1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(Po1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(Po2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PantallaInicial regresar = new PantallaInicial();
        this.setVisible(false);
        regresar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            if ((Double.parseDouble(tasaLlegada.getText()) < Double.parseDouble(tasaServicio.getText()))) {
                //|| Min.isSelected() || Sec.isSelected() || Min2.isSelected() || Sec2.isSelected()
                Calcular();
            } else {
                JOptionPane.showMessageDialog(rootPane, "La tasa de llegada tiene que ser menor a la tasa de servicio");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error, revise las entradas!");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void Act2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Act2ActionPerformed
        if(Act2.isSelected()){
            Wq.setEnabled(true);
        }else{
            Wq.setEnabled(false);
        }
    }//GEN-LAST:event_Act2ActionPerformed

    private void Act4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Act4ActionPerformed
        if(Act4.isSelected()){
            Ws.setEnabled(true);
        }else{
            Ws.setEnabled(false);
        }
    }//GEN-LAST:event_Act4ActionPerformed

    private void Act1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Act1ActionPerformed
       if(Act1.isSelected()){
            Ls.setEnabled(true);
        }else{
            Ls.setEnabled(false);
        } 
    }//GEN-LAST:event_Act1ActionPerformed

    private void Act3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Act3ActionPerformed
        if(Act3.isSelected()){
            Lq.setEnabled(true);
        }else{
            Lq.setEnabled(false);
        } 
    }//GEN-LAST:event_Act3ActionPerformed

    public void Calcular() {

        try {
            limpiarMatriz();
            Tsllegada = Double.parseDouble(tasaLlegada.getText());
            TsServicio = Double.parseDouble(tasaServicio.getText());
            calculoTiempo();
            calculoTiempo2();

            //Wq1 = calcular.CalcularWq(TsServicio, Tsllegada);
            //Ws1 = calcular.CalcularWs(Wq1, TsServicio);
            Wq1();
            Ws1();
            Ls1();
            Lq1();
            //Ls1 = calcular.CalcularLs(Tsllegada, Ws1);
            //Lq1 = calcular.CalcularLq(Tsllegada, Wq1);

            Wq.setText(String.valueOf(Wq1));
            Ws.setText(String.valueOf(Ws1));
            Ls.setText(String.valueOf(Ls1));
            Lq.setText(String.valueOf(Lq1));

            P1 = calcular.CalculaP(TsServicio, Tsllegada);
            p0 = calcular.CalculaOcio(P1);

            P.setText(String.valueOf(P1));
            Po.setText(String.valueOf(p0));

            confirmar = n1.getText();

            if (!"".equals(confirmar)) {
                n = Integer.parseInt(n1.getText());
                Pn = new double[n + 1];
                Pn = calcular.calculoPn(p0, P1, n);
                LlenarMatriz(Pn, n);
                DibujarProbabilidad(Pn, n);
            }

            if (!"".equals(t1.getText())) {
                tiempo = Integer.parseInt(t1.getText());
                tsL = new double[tiempo + 1];
                tsS = new double[tiempo + 1];
                tsL = calcular.TasaLl(Tsllegada, tiempo);
                tsS = calcular.TasaSer(TsServicio, tiempo);

                DibujarTasaLllegada(tsL, tiempo);
                DibujarTasaServicio(tsS, tiempo);

                tiempoMinutos1 = calcular.Wqt(TsServicio, P1, tiempo);
                tiempoMinutos2 = calcular.Wst(TsServicio, P1, tiempo);
                Po1.setText(String.valueOf(tiempoMinutos1));
                Po2.setText(String.valueOf(tiempoMinutos2));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Los datos ingresados deben ser numericos decimales.");
        }

    }

    public void LlenarMatriz(double pn[], int n) {
        for (int ctn = 0; ctn < n + 1; ctn++) {
            modTabM.addRow(new Object[]{
                String.valueOf(ctn), String.valueOf(pn[ctn])
            });
        }
    }

    private void limpiarMatriz() {
        int filas = modTabM.getRowCount();
        for (int a = 0; a < filas; a++) {
            modTabM.removeRow(0);
        }
    }

    public void calculoTiempo() {
        if (Min.isSelected()) {
            Tsllegada = Tsllegada / 60;
        } else if (Sec.isSelected()) {
            Tsllegada = Tsllegada / 3600;
        }

    }

    public void calculoTiempo2() {
        if (Min2.isSelected()) {
            TsServicio = TsServicio / 60;
        } else if (Sec2.isSelected()) {
            TsServicio = TsServicio / 3600;
        }

    }
    
    public void Wq1 (){
        if(Act2.isSelected()){
            Wq1 = Double.valueOf(Wq.getText());
        }else{
            Wq1 = calcular.CalcularWq(TsServicio, Tsllegada);
        }
    }
    
    public void Ws1(){
        if(Act4.isSelected()){
            Ws1 = Double.valueOf(Ws.getText());
        }else{
            Ws1 = calcular.CalcularWs(Wq1, TsServicio);
        }
    
    }
    
    public void Ls1(){
        if(Act1.isSelected()){
            Ls1 = Double.valueOf(Ls.getText());
            Ws1 = calcular.Ws2(Ls1, Tsllegada);
        }else{
            Ls1 = calcular.CalcularLs(Tsllegada, Ws1);
        }
    }
    
    public void Lq1(){
        if(Act3.isSelected()){
            Lq1 = Double.valueOf(Lq.getText());
            Wq1 = calcular.Wq2(Lq1, Tsllegada);
            Ls1 = calcular.Ls2(Lq1, Tsllegada,TsServicio);
        }else{
            Lq1 = calcular.CalcularLq(Tsllegada, Wq1);
        }
    
    }

    public void DibujarTasaLllegada(double valoresProb[], double tiempo) {
        DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
        for (int re = 0; re <= tiempo; re++) {
            dtsc.setValue(valoresProb[re], "Probabilidad", String.valueOf(re));
        }
        JFreeChart grafica = ChartFactory.createBarChart3D("Tasa de Llegada", "Tiempo", "No. de llegadas", dtsc, PlotOrientation.VERTICAL, true, true, false);

        ChartPanel pa = new ChartPanel(grafica);
        /*add(pa);
        pa.setBounds(0, 50, 600, 300);
        panel.add(pa, BorderLayout.NORTH);*/
        pa.setMouseWheelEnabled(true);
        pa.setPreferredSize(new Dimension(440, 240));
        panel1.setLayout(new BorderLayout());
        panel1.add(pa, BorderLayout.NORTH);
        pack();
        //repaint();

    }

    public void DibujarTasaServicio(double valoresProb[], double tiempo) {
        DefaultCategoryDataset dtsc = new DefaultCategoryDataset();
        for (int re = 0; re <= tiempo; re++) {
            dtsc.setValue(valoresProb[re], "Probabilidad", String.valueOf(re));
        }
        JFreeChart grafica = ChartFactory.createBarChart3D("Tasa de Servicio", "Tiempo", "Servicios", dtsc, PlotOrientation.VERTICAL, true, true, false);

        ChartPanel pa = new ChartPanel(grafica);
        /*add(pa);
        pa.setBounds(0, 50, 600, 300);
        panel.add(pa, BorderLayout.NORTH);*/
        pa.setMouseWheelEnabled(true);
        pa.setPreferredSize(new Dimension(440, 240));
        panel2.setLayout(new BorderLayout());
        panel2.add(pa, BorderLayout.NORTH);
        pack();
        //repaint();

    }

    public void DibujarProbabilidad(double valoresProb[], double tiempo) {
        XYSeries series = new XYSeries("Gráfica de probabilidad");

        XYSeriesCollection dtsc = new XYSeriesCollection();

        for (int re = 0; re <= tiempo; re++) {
            series.add(re, valoresProb[re]);
        }

        dtsc.addSeries(series);

        JFreeChart grafica = ChartFactory.createScatterPlot("Probabilidad n clientes", "Clientes", "Probabilidad", dtsc, PlotOrientation.VERTICAL, true, false, false);

        ChartPanel pa = new ChartPanel(grafica);
        /*add(pa);
        pa.setBounds(0, 50, 600, 300);
        panel.add(pa, BorderLayout.NORTH);*/
        pa.setMouseWheelEnabled(true);
        pa.setPreferredSize(new Dimension(440, 240));
        panel3.setLayout(new BorderLayout());
        panel3.add(pa, BorderLayout.NORTH);
        pack();
        //repaint();    
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mm1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Act1;
    private javax.swing.JCheckBox Act2;
    private javax.swing.JCheckBox Act3;
    private javax.swing.JCheckBox Act4;
    private javax.swing.JTextField Lq;
    private javax.swing.JTextField Ls;
    private javax.swing.JCheckBox Min;
    private javax.swing.JCheckBox Min2;
    private javax.swing.JTextField P;
    private javax.swing.JTextField Po;
    private javax.swing.JTextField Po1;
    private javax.swing.JTextField Po2;
    private javax.swing.JCheckBox Sec;
    private javax.swing.JCheckBox Sec2;
    private javax.swing.JTextField Wq;
    private javax.swing.JTextField Ws;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField n1;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JTextField t1;
    private javax.swing.JTable tablaM;
    private javax.swing.JTextField tasaLlegada;
    private javax.swing.JTextField tasaServicio;
    // End of variables declaration//GEN-END:variables
}
