/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wexpresionesregulares;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author Wilson Pop
 */
public class Exregular extends javax.swing.JFrame {

    /**
     * Creates new form Exregular
     */
    public Exregular() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    String patron="";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        in1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        in2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        vl1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        coin1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        in1.setForeground(new java.awt.Color(255, 0, 51));
        in1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                in1ActionPerformed(evt);
            }
        });

        in2.setColumns(20);
        in2.setForeground(new java.awt.Color(102, 51, 255));
        in2.setRows(5);
        jScrollPane1.setViewportView(in2);

        jLabel1.setText("Escriba el patrón a buscar");

        jLabel2.setText("Escriba el texto a evaluar");

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jButton1.setText("Evaluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        vl1.setBackground(new java.awt.Color(255, 102, 102));
        vl1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        vl1.setForeground(new java.awt.Color(204, 0, 204));
        vl1.setText("Validación");
        vl1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Swis721 LtCn BT", 3, 11)); // NOI18N
        jLabel3.setText("Wilson Victor Alexander Pop Cac -201840972 -Examen privado - ciencias de la computacion");

        jLabel5.setFont(new java.awt.Font("Sitka Text", 3, 11)); // NOI18N
        jLabel5.setText("Posiciones de las coincidencias:");

        coin1.setColumns(20);
        coin1.setForeground(new java.awt.Color(102, 204, 0));
        coin1.setRows(5);
        jScrollPane2.setViewportView(coin1);

        jButton2.setText("Empezar de nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Números binarios");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Valor Numerico");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(in1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(134, 134, 134))))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(vl1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel1)
                                .addGap(161, 161, 161)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(in1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(5, 5, 5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(15, 15, 15)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(vl1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void in1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_in1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_in1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
              
        
        String ent = this.in1.getText();
        String ent2 = this.in2.getText();
        
              
        
            Pattern pat = Pattern.compile(ent);
            Matcher ev = pat.matcher(ent2);
            boolean coin = ev.find();
            String am = ev.replaceAll("_");
            String ac = "";
            String ac2 = "";
            int cont = 0;
            //Puede servir
            /*System.out.println(ev.matches()); 
            System.out.println(ev.lookingAt());
             while(ev.find()){
                    cont ++;
                     ac += "Coincidencia No.  " + cont + " Desde posición " + ev.start() + " hasta posición " + ev.end() + "\n";
                }
            */
             ev.reset();
             while(ev.find()){
                 cont++;
                 ac += ev.group()+" = Coincidencia No.  " + cont + " Desde posición " + ev.start() + " hasta posición " + (ev.end()-1) + "\n";
             }
             
             
            if(coin==true){             
                
                vl1.setText("Existen coincidencias.");
                in2.setText(ent2+"\n"+am);
                coin1.setText(ac);
                                                
            }else{
                vl1.setText("No existen coincidencias.");
                
            }
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        in2.setText("");
        in1.setText("");
        coin1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        patron = "(0|1)+";
        
        String ent = patron;
        this.in1.setText(patron);
        String ent2 = this.in2.getText();
        
              
        
            Pattern pat = Pattern.compile(ent);
            Matcher ev = pat.matcher(ent2);
            boolean coin = ev.find();
            String am = ev.replaceAll("_");
            String ac = "";
            String ac2 = "";
            int cont = 0;
            //Puede servir
            /*System.out.println(ev.matches()); 
            System.out.println(ev.lookingAt());
             while(ev.find()){
                    cont ++;
                     ac += "Coincidencia No.  " + cont + " Desde posición " + ev.start() + " hasta posición " + ev.end() + "\n";
                }
            */
             ev.reset();
             while(ev.find()){
                 cont++;
                 ac += ev.group()+" = Coincidencia No.  " + cont + " Desde posición " + ev.start() + " hasta posición " + (ev.end()-1) + "\n";
             }
             
             
            if(coin==true){             
                
                vl1.setText("Existen coincidencias.");
                in2.setText(ent2+"\n"+am);
                coin1.setText(ac);
                                                
            }else{
                vl1.setText("No existen coincidencias.");
                
            }
            
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        patron = "(-)?[0-9]{2}";
        
        String ent = patron;
        this.in1.setText(patron);
        String ent2 = this.in2.getText();
        
            int suma = 0;
            int resta =0;
            String acumulador[] = new String[patron.length()];
            String acumulador2[] = new String[patron.length()];
            int contador =0;
            Pattern pat = Pattern.compile(ent);
            Matcher ev = pat.matcher(ent2);
            boolean coin = ev.find();
            String am = ev.replaceAll("_");
            String ac = "";
            String ac2 = "";
            int cont = 0;
            //Puede servir
            /*System.out.println(ev.matches()); 
            System.out.println(ev.lookingAt());
             while(ev.find()){
                    cont ++;
                     ac += "Coincidencia No.  " + cont + " Desde posición " + ev.start() + " hasta posición " + ev.end() + "\n";
                }
            */
             ev.reset();
             
           
             
             while(ev.find()){
                 acumulador[cont]=ev.group();
                 acumulador2[cont]=ev.group();
                 cont++;
                 ac += ev.group()+" = Coincidencia No.  " + cont + " Desde posición " + ev.start() + " hasta posición " + (ev.end()-1) + "\n";
                 
             }
             
             for(int i=0;i<ent2.length();i++){
                 System.out.println("--");
                 if(acumulador2[i+1].equals(null)){
                     JOptionPane.showMessageDialog(rootPane, "---");
                 }
                 else if(acumulador2[i+1]!=null){
                     if(acumulador[i].equals(acumulador2[i+1])){
                         ac+="\n"+ acumulador[i]+ " y" +acumulador2[i+1]+ " son iguales" +" su suma es: "+
                                 String.valueOf(Integer.parseInt(acumulador[i] + acumulador2[i])) + " su resta es: " + "- " +String.valueOf(Integer.parseInt(acumulador[i] + acumulador2[i]));
                     }else{
                           ac+="\n"+ acumulador[i]+ " y" +acumulador2[i+1]+ " son diferentes" +" su suma es: "+
                                 String.valueOf(Integer.parseInt(acumulador[i] + acumulador2[i])) + " su resta es: " + "- " +String.valueOf(Integer.parseInt(acumulador[i] + acumulador2[i]));
                     }
                 }
             
             }
            
             
             
            if(coin==true){             
                
                vl1.setText("Existen coincidencias.");
                in2.setText(ent2+"\n"+am);
                coin1.setText(ac);
                                                
            }else{
                vl1.setText("No existen coincidencias.");
                
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exregular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exregular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exregular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exregular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exregular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea coin1;
    private javax.swing.JTextField in1;
    private javax.swing.JTextArea in2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel vl1;
    // End of variables declaration//GEN-END:variables
}
