/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbolito;

import javax.swing.JOptionPane;

/**
 *
 * @author Wilson Pop
 */
public class Mostrar extends javax.swing.JFrame {

    /**
     * Creates new form Mostrar
     */
    public Mostrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txta.setColumns(20);
        txta.setRows(5);
        jScrollPane1.setViewportView(txta);

        jLabel1.setText("No. Nodos");

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addContainerGap(166, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int lot = Integer.parseInt(this.txt4.getText());
        String ma [][];
        ma = new String [lot][4];
        String fila1= "ID                   P                   HZ                  HD" + "\n";
        String al = fila1;    
        
        
        for(int fil=0;fil<lot;fil++){
                for(int col=0;col<4;col++){
                    if(col==0){
                        ma[fil][col]=JOptionPane.showInputDialog("Escriba la id No." + (fil+1));
                    }
                    if(col==1){
                        ma[fil][col]=JOptionPane.showInputDialog("Escriba el padre No." + (fil+1));
                        for(int aa=0;aa<lot;aa++){
                            for(int bb=0;bb<4;bb++){
                                if(ma[fil][col].equals(ma[aa][bb])){
                                    if(aa !=fil && bb==1){
                                        ma[fil][col]=JOptionPane.showInputDialog("Este padre ya aparece en otra casilla, por favor vuelva a escribirlo para evitar confusión" );
                                    }
                                    else if(aa== fil && bb ==2){
                                        ma[fil][col]=JOptionPane.showInputDialog("El padre se parece a un hijo izquierdo, debe cambiarlo");
                                    }
                                    else if(aa !=fil && bb==2){
                                        ma[fil][col]=JOptionPane.showInputDialog("El padre se parece a un hijo izquierdo, debe cambiarlo");
                                    }
                                    else if(aa==fil && bb == 3){
                                        ma[fil][col]=JOptionPane.showInputDialog("El padre se parece a un hijo derecho, debe cambiarlo");                                    
                                    }
                                    else if(aa!=fil && bb==3){
                                        ma[fil][col]=JOptionPane.showInputDialog("El padre se parece a un hijo derecho, debe cambiarlo");
                                    }
                                    else{break;}
                                }
                            }
                        }
                    }
                    if(col==2){
                        ma[fil][col]=JOptionPane.showInputDialog("Escriba el hijo izquierdo No." + (fil+1));
                           for(int rr=0;rr<lot;rr++){
                               for(int ll=0;ll<4;ll++){
                                   if(ma[fil][col].equals(ma[rr][ll])){
                                      if(rr ==fil && ll==1){
                                          JOptionPane.showInputDialog("Hay una coincidencia, vuelva a escribir");
                                      }
                                      else if(rr ==fil && ll==3){
                                          JOptionPane.showInputDialog("Hay una coincidencia, vuelva a escribir");
                                      }
                                      else if(rr!=fil && ll==1){
                                          JOptionPane.showInputDialog("Hay una coincidencia, vuelva a escribir");
                                      }
                                      else if(rr!=fil && ll==2){
                                          JOptionPane.showInputDialog("Hay una coincidencia, vuelva a escribir");
                                      }
                                      else if(rr!=fil && ll==3){
                                          JOptionPane.showInputDialog("Hay una coincidencia, vuelva a escribir");
                                      }
                                      
                                   }
                               }
                           }
                    }
                    if(col==3){
                        ma[fil][col]=JOptionPane.showInputDialog("Escriba el hijo derecho No." + (fil+1));
                            for(int mm=0;mm<lot;mm++){
                               for(int nn=0;nn<4;nn++){
                                   if(ma[fil][col].equals(ma[mm][nn])){
                                      if(mm ==fil && nn==1){
                                          JOptionPane.showInputDialog("Hay una coincidencia, vuelva a escribir");
                                      }
                                      else if(mm==fil && nn==2){
                                          JOptionPane.showInputDialog("Hay una coincidencia, vuelva a escribir");
                                      }
                                      else if(mm!=fil && nn==1){
                                          JOptionPane.showInputDialog("Hay una coincidencia, vuelva a escribir");
                                      }
                                      else if(mm!=fil && nn==2){
                                          JOptionPane.showInputDialog("Hay una coincidencia, vuelva a escribir");
                                      }
                                      else if(mm!=fil && nn==3){
                                          JOptionPane.showInputDialog("Hay una coincidencia, vuelva a escribir");
                                      }
                                      
                                   }
                               }
                           }
                    }
                }
        
            }         
           
              
        
            for(int fil1=0;fil1<lot;fil1++){
                for(int col2=0;col2<4;col2++){
                    al += ma[fil1][col2] + "                    ";
                    if(col2==3){
                        al = al + "\n";
                    }
                }
            }
           
           
            
            txta.setText(al);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextArea txta;
    // End of variables declaration//GEN-END:variables
}
