/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package matriz_arbol;

import javax.swing.JOptionPane;

/**
 *
 * @author Wilson Pop
 */
public class Matrizarbol extends javax.swing.JFrame {

    /**
     * Creates new form Matrizarbol
     */
    public Matrizarbol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta = new javax.swing.JTextArea();
        Nodos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txta.setColumns(20);
        txta.setRows(5);
        jScrollPane1.setViewportView(txta);

        Nodos.setText("Nodos");

        jButton1.setText("Empezar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Nodos)
                        .addGap(30, 30, 30)
                        .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nodos))
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int lot = Integer.parseInt(this.txt4.getText());
        String ma [][];
        ma = new String [lot][4];
        String fila1= "ID                   P                   HZ                  HD" + "\n";
        String al = fila1;    
        
        
        for(int fil=0;fil<lot;fil++){
                for(int col=0;col<4;col++){
                    if(col==0){
                        ma[fil][col]=JOptionPane.showInputDialog("Escriba la id No." + (fil+1));
                    }
                    if(col==1){
                        ma[fil][col]=JOptionPane.showInputDialog("Escriba el padre No." + (fil+1));
                        for(int aa=0;aa<lot;aa++){
                            for(int bb=0;bb<4;bb++){
                                if(ma[fil][col].equals(ma[aa][bb])){
                                    if(aa !=fil && bb==1){
                                        ma[fil][col]=JOptionPane.showInputDialog("Este padre ya aparece en otra casilla, por favor vuelva a escribirlo para evitar confusión" );
                                    }
                                    else if(bb ==2){
                                        ma[fil][col]=JOptionPane.showInputDialog("El padre se parece a un hijo izquierdo, debe cambiarlo");
                                    }
                                    else if(bb == 3){
                                        ma[fil][col]=JOptionPane.showInputDialog("El padre se parece a un hijo derecho, debe cambiarlo");                                    
                                    }
                                    else{break;}
                                }
                            }
                        }
                    }
                    if(col==2){
                        ma[fil][col]=JOptionPane.showInputDialog("Escriba el hijo izquierdo No." + (fil+1));
                    }
                    if(col==3){
                        ma[fil][col]=JOptionPane.showInputDialog("Escriba el hijo derecho No." + (fil+1)); 
                    }
                }
        
            }         
           
              
        
            for(int fil1=0;fil1<lot;fil1++){
                for(int col2=0;col2<4;col2++){
                    al += ma[fil1][col2] + "                    ";
                    if(col2==3){
                        al = al + "\n";
                    }
                }
            }
           
           
            
            txta.setText(al);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matrizarbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matrizarbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matrizarbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matrizarbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matrizarbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nodos;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextArea txta;
    // End of variables declaration//GEN-END:variables
}
